services:
  # Define el servicio web
  web:
    build: .
    container_name: webserver
    ports:
      - "80:80"
      - "9003:9003"
    volumes:
      - .:/var/www/html 
    networks:
      - web_network
    restart: always
    depends_on:
      - db

  # Define el servicio de BD
  db:
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - web_network
    restart: always
 
# Define el servicio de Dbeaver
  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    ports:
      - 8082:8978
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - web_network
    restart: always


volumes:
  dbeaver_data:
  database_data:

networks:
  web_network:
    driver: bridge
